### ISSUE TITLE
Feature Request: Provision to set sync.media.dest

### ISSUE THREAD

**Issue by rajeev-k-tomy** [staempfli/magento2-builder-tool#5]
It would be great if we have a provision to set the parameter `sync.media.dest`. Currently, this value is depending on the value `sync.media.dir` which we can alter through a configuration file. But in case we need a separate parameter value for `sync.media.dest`, the current configuration won't allow doing the same.

This conflict normally won't happen. But we can expect the same if the remote server has all the Magento related files in the root directory and in our development we are following the rule **all core code in `magento` folder** or vice versa.

**Comment by jalogut** [comment]
Hi @progammer-rkt 

Sure, could you create a PR for that? Just check how `sync.media.dir` works and do something similar for `sync.media.dest`. I will be glad to check and accept that PR.
