### ISSUE TITLE
Question: How to avoid test tables related commands; How to avoid removing backup tables

### ISSUE THREAD

**Issue by rajeev-k-tomy** [staempfli/magento2-builder-tool#6]
As you can see in the heading, basically I have two questions here. It would be great if you can suggest some solution for the same.

**1. How to avoid test tables related commands**

When I run the `sync` command, I observed that it always run test related commands. i.e, it creates a new DB for the test and does other kinds of stuff. How can avoid this?

**2. How to avoid removing backup tables**

During the process of `sync` command, it looks like, the process backups both remote and local DBs and in the later stage, it will remove the backup DB from the local machine. How can avoid this?

I am expecting the solution would write our own custom commands through `custom.xml`.  If there is any other solution does exist, please let us know.

**Comment by jalogut** [comment]
Hi @progammer-rkt 

Sorry for the late reply:

**1.** You can execute the commands passing the flag `skipIntegration`

```
bin/mg2-builder install -Dskipintegration
bin/mg2-builder sync -Dskipintegration
```

**2.** The process does not create any backup from local. We overwrite everything with the remote dump created. If you want to create a backup of your local you could overwrite the `database:drop` command to create a backup first:

* on `custom.xml` add:
```
<target name="database:drop"
            hidden="true">

        <!-- Here your command to create a local backup -->

        <!-- Original code to drop the database -->
        <property name="command.drop.database"
                  value="${bin.n98-magerun2} db:drop -f --connection=${database.connection.type}"
                  override="true"/>
        <echo message="${command.drop.database}"/>
        <exec command="${command.drop.database}" checkreturn="false" logoutput="true"/>

</target>
```
