### ISSUE TITLE
DB host port

### ISSUE THREAD

**Issue by galanis-a** [staempfli/magento2-builder-tool#8]
Hello

i started using m2 builder and noticed that i can't set the port for the DB host. I'm mentioning it cause in my dev environment i my db instance in another server on the network, with multiple mysql instances that run on different ports than 3306.

It could have 3306 as default value and can be overwritten in build.properties file.

Also i think a user host would be nice to set the mysql user host in something like % or localhost independent from the db host setting.

I can make the changes and make a PR if you want.

Thanks

**Comment by jalogut** [comment]
Hi @galanis-a 

Sure, if would be great if you could create a PR. For the host there is already a variable that you can overwrite (`database.host`)

For the port, you would have to edit following line to add the port on the connection command:
* https://github.com/staempfli/magento2-builder-tool/blob/1ab8219021a59968b7205eeb2b8068b9db478442/build/xmlscripts/database.xml#L45
